export const LOGGER_CONSTANTS = {
  MAX_LOG_SIZE: 10000,
  COMPRESSION_THRESHOLD: 5000,
  RECENT_LOGS_COUNT: 100,
  COMPRESS_RECENT_LOGS_COUNT: 1000,
} as const;

export const MEMORY_MONITOR_CONSTANTS = {
  MEMORY_LIMIT_MB: 512,
  BYTES_PER_MB: 1024 * 1024,
  CHECK_INTERVAL_MS: 10000,
  THRESHOLD_RATIO: 0.9,
  PERCENTAGE_MULTIPLIER: 100,
} as const;

export const LOG_LEVELS = {
  DEBUG: "DEBUG",
  INFO: "INFO",
  WARN: "WARN",
  ERROR: "ERROR",
  FATAL: "FATAL",
} as const;

export const LOG_VISIBILITY = {
  PUBLIC: "PUBLIC",
  INTERNAL: "INTERNAL",
  DEBUG: "DEBUG",
  TRACE: "TRACE",
} as const;
