import type { UserRepository } from "@/domain/repositories/UserRepository";
import type { User, UserRole } from "@/schemas/api";

/**
 * Result of an authentication operation.
 *
 * Contains the authenticated user and a session token.
 */
export interface AuthenticationResult {
  user: User;
  token: string;
}

/**
 * Error thrown when authentication fails.
 */
export class AuthenticationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "AuthenticationError";
  }
}

/**
 * Password hashing interface for dependency injection.
 *
 * This abstraction allows the domain layer to remain independent of
 * specific password hashing implementations (bcrypt, argon2, etc.).
 * Implementations are provided by the infrastructure layer.
 *
 * @example
 * ```ts
 * class BcryptPasswordHasher implements PasswordHasher {
 *   async hash(password: string): Promise<string> {
 *     return await bcrypt.hash(password, 10);
 *   }
 *   async verify(password: string, hash: string): Promise<boolean> {
 *     return await bcrypt.compare(password, hash);
 *   }
 * }
 * ```
 */
export interface PasswordHasher {
  /**
   * Hash a plain text password.
   *
   * @param password - Plain text password to hash.
   * @returns Promise resolving to the hashed password.
   */
  hash(password: string): Promise<string>;

  /**
   * Verify a plain text password against a hash.
   *
   * @param password - Plain text password to verify.
   * @param hash - Hash to compare against.
   * @returns Promise resolving to true if password matches, false otherwise.
   */
  verify(password: string, hash: string): Promise<boolean>;
}

/**
 * Token generation interface for session management.
 *
 * Abstracts token generation logic, allowing different implementations
 * (JWT, opaque tokens, UUIDs, etc.) to be injected.
 *
 * @example
 * ```ts
 * class UuidTokenGenerator implements TokenGenerator {
 *   async generateToken(user: User): Promise<string> {
 *     return `session-${user.id}-${Date.now()}-${crypto.randomUUID()}`;
 *   }
 * }
 * ```
 */
export interface TokenGenerator {
  /**
   * Generate a session token for a user.
   *
   * @param user - User to generate token for.
   * @returns Promise resolving to the generated token.
   */
  generateToken(user: User): Promise<string>;
}

/**
 * Domain service for user authentication.
 *
 * Handles authentication business logic including password hashing,
 * login/logout operations, and session token generation.
 *
 * **Security Policies:**
 * - Passwords are hashed using injected PasswordHasher (never stored plain text)
 * - Login attempts are rate-limited (enforced by application layer)
 * - Sessions are tracked via tokens generated by TokenGenerator
 *
 * **Validation Rules:**
 * - Email must exist in repository
 * - Password must match stored hash
 * - User must have valid role (TEACHER or ADMIN)
 *
 * @example
 * ```ts
 * const hasher = new BcryptPasswordHasher();
 * const tokenGen = new UuidTokenGenerator();
 * const authService = new AuthenticationService(userRepo, hasher, tokenGen);
 *
 * const result = await authService.login("teacher@example.com", "password123");
 * console.log(result.user.name); // "John Doe"
 * console.log(result.token); // "session-1-1234567890-abc123"
 * ```
 */
export class AuthenticationService {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly passwordHasher: PasswordHasher,
    private readonly tokenGenerator: TokenGenerator,
  ) {}

  /**
   * Authenticate a user with email and password.
   *
   * **Validation:**
   * 1. Email must be registered
   * 2. Password must match stored hash
   * 3. User must have valid role
   *
   * **Security:**
   * - Uses constant-time comparison to prevent timing attacks (delegated to PasswordHasher)
   * - Does not reveal whether email exists (generic error message)
   *
   * @param email - User's email address.
   * @param password - Plain text password.
   * @returns Promise resolving to AuthenticationResult with user and token.
   * @throws AuthenticationError if authentication fails.
   */
  async login(email: string, password: string): Promise<AuthenticationResult> {
    const normalizedEmail = this.normalizeEmail(email);

    const user = await this.userRepository.findByEmail(normalizedEmail);

    if (!user) {
      throw new AuthenticationError("Invalid email or password");
    }

    const isValid = await this.passwordHasher.verify(password, user.passwordHash);

    if (!isValid) {
      throw new AuthenticationError("Invalid email or password");
    }

    const token = await this.tokenGenerator.generateToken(user);

    return {
      user,
      token,
    };
  }

  /**
   * Register a new user account.
   *
   * **Validation:**
   * 1. Email must not already be registered
   * 2. Password must meet strength requirements (min 8 characters)
   * 3. Name must not be empty
   * 4. Role must be valid (TEACHER or ADMIN)
   *
   * **Security:**
   * - Password is hashed before storage
   * - Email is normalized (lowercased, trimmed)
   *
   * @param email - User's email address.
   * @param password - Plain text password (will be hashed).
   * @param name - User's display name.
   * @param role - User's role (TEACHER or ADMIN).
   * @returns Promise resolving to the created user.
   * @throws AuthenticationError if validation fails.
   */
  async register(
    email: string,
    password: string,
    name: string,
    role: UserRole,
  ): Promise<User> {
    const normalizedEmail = this.normalizeEmail(email);
    const trimmedName = name.trim();

    if (trimmedName.length === 0) {
      throw new AuthenticationError("Name cannot be empty");
    }

    if (password.length < 8) {
      throw new AuthenticationError("Password must be at least 8 characters");
    }

    const emailExists = await this.userRepository.emailExists(normalizedEmail);

    if (emailExists) {
      throw new AuthenticationError("Email already registered");
    }

    const passwordHash = await this.passwordHasher.hash(password);

    const newUser: User = {
      email: normalizedEmail,
      passwordHash,
      name: trimmedName,
      role,
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    return await this.userRepository.save(newUser);
  }

  /**
   * Verify a session token and return the associated user.
   *
   * This is a simplified implementation that extracts the user ID from
   * the token and looks up the user. In production, this should validate
   * the token cryptographically and check expiration.
   *
   * @param token - Session token to verify.
   * @returns Promise resolving to the authenticated user.
   * @throws AuthenticationError if token is invalid.
   */
  async verifyToken(token: string): Promise<User> {
    if (!token || token.length === 0) {
      throw new AuthenticationError("Invalid token");
    }

    const userId = this.extractUserIdFromToken(token);

    if (!userId) {
      throw new AuthenticationError("Invalid token format");
    }

    const user = await this.userRepository.findById(userId);

    if (!user) {
      throw new AuthenticationError("User not found");
    }

    return user;
  }

  /**
   * Change a user's password.
   *
   * **Validation:**
   * 1. User must exist
   * 2. Current password must match
   * 3. New password must meet strength requirements
   * 4. New password must differ from current password
   *
   * @param userId - User's ID.
   * @param currentPassword - Current plain text password.
   * @param newPassword - New plain text password.
   * @returns Promise resolving when password is changed.
   * @throws AuthenticationError if validation fails.
   */
  async changePassword(
    userId: number,
    currentPassword: string,
    newPassword: string,
  ): Promise<void> {
    const user = await this.userRepository.findById(userId);

    if (!user) {
      throw new AuthenticationError("User not found");
    }

    const isCurrentPasswordValid = await this.passwordHasher.verify(
      currentPassword,
      user.passwordHash,
    );

    if (!isCurrentPasswordValid) {
      throw new AuthenticationError("Current password is incorrect");
    }

    if (newPassword.length < 8) {
      throw new AuthenticationError("New password must be at least 8 characters");
    }

    const isCurrentPasswordSame = await this.passwordHasher.verify(
      newPassword,
      user.passwordHash,
    );

    if (isCurrentPasswordSame) {
      throw new AuthenticationError("New password must be different from current password");
    }

    const newPasswordHash = await this.passwordHasher.hash(newPassword);

    const updatedUser: User = {
      ...user,
      passwordHash: newPasswordHash,
      updatedAt: new Date(),
    };

    await this.userRepository.save(updatedUser);
  }

  /**
   * Normalize an email address for consistent storage and comparison.
   *
   * Normalization includes:
   * - Converting to lowercase
   * - Trimming whitespace
   *
   * @param email - Email address to normalize.
   * @returns Normalized email address.
   */
  private normalizeEmail(email: string): string {
    return email.toLowerCase().trim();
  }

  /**
   * Extract user ID from a session token.
   *
   * This is a simplified implementation that parses a token format like
   * "session-{userId}-{timestamp}-{random}". In production, this should
   * decode and validate a JWT or similar cryptographically secure token.
   *
   * @param token - Session token.
   * @returns User ID or null if extraction fails.
   */
  private extractUserIdFromToken(token: string): number | null {
    const parts = token.split("-");

    if (parts[0] !== "session" || parts.length < 2) {
      return null;
    }

    const userId = parseInt(parts[1], 10);

    if (isNaN(userId) || userId <= 0) {
      return null;
    }

    return userId;
  }
}
